{
 "title": "InstalingBot",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "Profiles",
    "query": "SELECT user_id AS __value, username AS __text FROM $dbname.Usernames;"
   },
   { "name": "dbname", "label": "Database name", "query": "${VAR_DBNAME}" }
  ]
 },
 "panels": [
  { "title": "Quick Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tasks Done",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "$dbname",
     "rawSql": "SELECT SUM(seen_times) FROM $dbname.WordHistory;"
    }
   ]
  },
  {
   "title": "Known Words",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "$dbname",
     "rawSql": "SELECT COUNT(*) FROM $dbname.Words;"
    }
   ]
  },
  {
   "title": "Unique Translations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "$dbname",
     "rawSql": "SELECT COUNT(DISTINCT translation) FROM $dbname.WordTranslations;"
    }
   ]
  },
  {
   "title": "Total Translations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "$dbname",
     "rawSql": "SELECT COUNT(*) FROM $dbname.WordTranslations;"
    }
   ]
  },
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Solved tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT $__time(timestamp), tasks AS \"Tasks done\"\nFROM $dbname.GlobalWordCountHistory\nUNION\nSELECT UNIX_TIMESTAMP(), SUM(seen_times) FROM $dbname.WordHistory;"
    }
   ]
  },
  {
   "title": "Dictionary size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n  $__time(timestamp), \n  words AS \"Words\", \n  translations AS \"Translations\", \n  unique_translations AS \"Unique Translations\"\nFROM $dbname.GlobalWordCountHistory\nUNION\nSELECT UNIX_TIMESTAMP(), (SELECT COUNT(*) FROM $dbname.Words), COUNT(id), COUNT(DISTINCT translation)\nFROM $dbname.WordTranslations"
    }
   ]
  },
  {
   "title": "Longest Entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Longest Single Translations",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "dataset": "$dbname",
       "rawSql": "SELECT\n  LENGTH(wt.translation) AS Length,\n  wt.translation AS Translation,\n  w.word AS Word\nFROM $dbname.WordTranslations wt INNER JOIN $dbname.Words w ON wt.word_id = w.id\nORDER BY Length DESC"
      }
     ]
    },
    {
     "title": "Longest Total Translations",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "dataset": "$dbname",
       "rawSql": "SELECT\n  SUM(LENGTH(wt.translation)) AS `Total Length`,\n  GROUP_CONCAT(wt.translation SEPARATOR ', ') AS Translations,\n  w.word AS Word\nFROM $dbname.WordTranslations wt INNER JOIN $dbname.Words w ON wt.word_id = w.id\nGROUP BY w.id\nORDER BY `Total Length` DESC"
      }
     ]
    },
    {
     "title": "Longest Definitions",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "dataset": "$dbname",
       "rawSql": "SELECT\n  LENGTH(w.word) AS Length,\n  w.word AS Word,\n  GROUP_CONCAT(wt.translation SEPARATOR ', ') AS Translations\nFROM $dbname.Words w INNER JOIN $dbname.WordTranslations wt ON w.id = wt.word_id\nGROUP BY w.id\nORDER BY Length DESC"
      }
     ]
    },
    {
     "title": "Longest Answers",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "dataset": "$dbname",
       "rawSql": "SELECT\n  LENGTH(w.shown_word) AS Length,\n  w.shown_word AS Answer,\n  GROUP_CONCAT(wt.translation SEPARATOR ', ') AS Translations\nFROM $dbname.Words w INNER JOIN $dbname.WordTranslations wt ON w.id = wt.word_id\nGROUP BY w.id\nORDER BY Length DESC"
      }
     ]
    },
    {
     "title": "Longest Usage Examples",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "dataset": "$dbname",
       "rawSql": "SELECT\n  LENGTH(w.usage_example) AS Length,\n  w.usage_example AS \"Usage Example\",\n  w.shown_word AS Word\nFROM $dbname.Words w\nORDER BY Length DESC"
      }
     ]
    },
    {
     "title": "Most Translations",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "dataset": "$dbname",
       "rawSql": "SELECT\n  COUNT(*) AS Count,\n  w.word AS Word,\n  GROUP_CONCAT(wt.translation SEPARATOR ', ') AS Translations\nFROM $dbname.Words w INNER JOIN $dbname.WordTranslations wt ON w.id = wt.word_id\nGROUP BY w.id\nORDER BY Count DESC"
      }
     ]
    },
    {
     "title": "Most Synonyms",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "dataset": "$dbname",
       "rawSql": "SELECT DISTINCT\n  COUNT(DISTINCT wt2.word_id) AS Count, \n  wt1.translation AS Translation,\n  GROUP_CONCAT(w.word SEPARATOR ', ') AS \"Matching Words\"\nFROM       $dbname.WordTranslations wt1 \nINNER JOIN $dbname.WordTranslations wt2 ON wt1.translation = wt2.translation \nINNER JOIN $dbname.Words w ON wt2.word_id = w.id\nGROUP BY wt1.id\nHAVING Count > 1\nORDER BY Count DESC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Profile stats: $user",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "user",
   "collapsed": true,
   "panels": [
    {
     "title": "Most commonly seen words",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "dataset": "$dbname",
       "rawSql": "SELECT \n  w.shown_word AS \"Word\", \n  w.usage_example AS \"Example\",\n  wh.seen_times AS \"Times seen\"\nFROM $dbname.WordHistory wh \nJOIN $dbname.Words w ON wh.word_id = w.id \nWHERE user_id = $user \nORDER BY wh.seen_times DESC \nLIMIT 50;"
      }
     ]
    },
    {
     "title": "Recent tasks",
     "type": "logs",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "dataset": "grafana",
       "rawSql": "SELECT \n  $__time(wh.last_seen),\n  w.usage_example AS \"Example\",\n  w.word AS \"Word\",\n  w.shown_word AS \"Answer\",\n  GROUP_CONCAT(wt.translation SEPARATOR \", \") AS \"Translations\",\n  wh.word_id AS \"Word ID\",\n  wh.seen_times AS \"Times seen\",\n  (CASE WHEN wh.seen_times <= 2 THEN \"warning\" ELSE CASE WHEN wh.seen_times <= 10 THEN \"info\" ELSE \"debug\" END END) AS level\nFROM $dbname.WordHistory wh \nJOIN $dbname.Words w ON wh.word_id = w.id\nJOIN $dbname.WordTranslations wt ON wt.word_id = w.id\nWHERE user_id = $user\nGROUP BY wt.word_id\nORDER BY wh.last_seen DESC\nLIMIT 50;"
      }
     ]
    },
    {
     "title": "Solved tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "dataset": "grafana",
       "rawSql": "SELECT $__time(timestamp), tasks AS \"Tasks done\"\nFROM $dbname.UserWordCountHistory\nWHERE user_id = $user\nUNION\nSELECT UNIX_TIMESTAMP(), SUM(seen_times)\nFROM $dbname.WordHistory\nWHERE user_id = $user;"
      }
     ]
    },
    {
     "title": "Dictionary size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "dataset": "grafana",
       "rawSql": "SELECT \n  $__time(timestamp), \n  words AS \"Words\", \n  translations AS \"Translations\", \n  unique_translations AS \"Unique Translations\"\nFROM $dbname.UserWordCountHistory\nWHERE user_id = $user\nUNION\nSELECT \n  UNIX_TIMESTAMP(), \n  COUNT(DISTINCT w.id),\n  COUNT(*),\n  COUNT(DISTINCT wt.translation)\nFROM $dbname.Words w\nJOIN $dbname.WordHistory wh ON w.id = wh.word_id\nJOIN $dbname.WordTranslations wt ON w.id = wt.word_id\nWHERE wh.user_id = $user;"
      }
     ]
    },
    {
     "title": "Run times (lifetime)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "dataset": "grafana",
       "rawSql": "SELECT\n    s.Hour AS \"Hour\",\n    SUM(TIME(sh.start_time) < s.`01` AND TIME(sh.end_time) >= s.`00`) AS \"00\",\n    SUM(TIME(sh.start_time) < s.`02` AND TIME(sh.end_time) >= s.`01`) AS \"01\",\n    SUM(TIME(sh.start_time) < s.`03` AND TIME(sh.end_time) >= s.`02`) AS \"02\",\n    SUM(TIME(sh.start_time) < s.`04` AND TIME(sh.end_time) >= s.`03`) AS \"03\",\n    SUM(TIME(sh.start_time) < s.`05` AND TIME(sh.end_time) >= s.`04`) AS \"04\",\n    SUM(TIME(sh.start_time) < s.`06` AND TIME(sh.end_time) >= s.`05`) AS \"05\",\n    SUM(TIME(sh.start_time) < s.`07` AND TIME(sh.end_time) >= s.`06`) AS \"06\",\n    SUM(TIME(sh.start_time) < s.`08` AND TIME(sh.end_time) >= s.`07`) AS \"07\",\n    SUM(TIME(sh.start_time) < s.`09` AND TIME(sh.end_time) >= s.`08`) AS \"08\",\n    SUM(TIME(sh.start_time) < s.`10` AND TIME(sh.end_time) >= s.`09`) AS \"09\",\n    SUM(TIME(sh.start_time) < s.`11` AND TIME(sh.end_time) >= s.`10`) AS \"10\",\n    SUM(TIME(sh.start_time) < s.`12` AND TIME(sh.end_time) >= s.`11`) AS \"11\",\n    SUM(TIME(sh.start_time) < s.`13` AND TIME(sh.end_time) >= s.`12`) AS \"12\",\n    SUM(TIME(sh.start_time) < s.`14` AND TIME(sh.end_time) >= s.`13`) AS \"13\",\n    SUM(TIME(sh.start_time) < s.`15` AND TIME(sh.end_time) >= s.`14`) AS \"14\",\n    SUM(TIME(sh.start_time) < s.`16` AND TIME(sh.end_time) >= s.`15`) AS \"15\",\n    SUM(TIME(sh.start_time) < s.`17` AND TIME(sh.end_time) >= s.`16`) AS \"16\",\n    SUM(TIME(sh.start_time) < s.`18` AND TIME(sh.end_time) >= s.`17`) AS \"17\",\n    SUM(TIME(sh.start_time) < s.`19` AND TIME(sh.end_time) >= s.`18`) AS \"18\",\n    SUM(TIME(sh.start_time) < s.`20` AND TIME(sh.end_time) >= s.`19`) AS \"19\",\n    SUM(TIME(sh.start_time) < s.`21` AND TIME(sh.end_time) >= s.`20`) AS \"20\",\n    SUM(TIME(sh.start_time) < s.`22` AND TIME(sh.end_time) >= s.`21`) AS \"21\",\n    SUM(TIME(sh.start_time) < s.`23` AND TIME(sh.end_time) >= s.`22`) AS \"22\",\n    SUM(TIME(sh.start_time) < s.`24` AND TIME(sh.end_time) >= s.`23`) AS \"23\",\n    SUM(TIME(sh.start_time) < s.`25` AND TIME(sh.end_time) >= s.`24`) AS \"24\",\n    SUM(TIME(sh.start_time) < s.`26` AND TIME(sh.end_time) >= s.`25`) AS \"25\",\n    SUM(TIME(sh.start_time) < s.`27` AND TIME(sh.end_time) >= s.`26`) AS \"26\",\n    SUM(TIME(sh.start_time) < s.`28` AND TIME(sh.end_time) >= s.`27`) AS \"27\",\n    SUM(TIME(sh.start_time) < s.`29` AND TIME(sh.end_time) >= s.`28`) AS \"28\",\n    SUM(TIME(sh.start_time) < s.`30` AND TIME(sh.end_time) >= s.`29`) AS \"29\",\n    SUM(TIME(sh.start_time) < s.`31` AND TIME(sh.end_time) >= s.`30`) AS \"30\",\n    SUM(TIME(sh.start_time) < s.`32` AND TIME(sh.end_time) >= s.`31`) AS \"31\",\n    SUM(TIME(sh.start_time) < s.`33` AND TIME(sh.end_time) >= s.`32`) AS \"32\",\n    SUM(TIME(sh.start_time) < s.`34` AND TIME(sh.end_time) >= s.`33`) AS \"33\",\n    SUM(TIME(sh.start_time) < s.`35` AND TIME(sh.end_time) >= s.`34`) AS \"34\",\n    SUM(TIME(sh.start_time) < s.`36` AND TIME(sh.end_time) >= s.`35`) AS \"35\",\n    SUM(TIME(sh.start_time) < s.`37` AND TIME(sh.end_time) >= s.`36`) AS \"36\",\n    SUM(TIME(sh.start_time) < s.`38` AND TIME(sh.end_time) >= s.`37`) AS \"37\",\n    SUM(TIME(sh.start_time) < s.`39` AND TIME(sh.end_time) >= s.`38`) AS \"38\",\n    SUM(TIME(sh.start_time) < s.`40` AND TIME(sh.end_time) >= s.`39`) AS \"39\",\n    SUM(TIME(sh.start_time) < s.`41` AND TIME(sh.end_time) >= s.`40`) AS \"40\",\n    SUM(TIME(sh.start_time) < s.`42` AND TIME(sh.end_time) >= s.`41`) AS \"41\",\n    SUM(TIME(sh.start_time) < s.`43` AND TIME(sh.end_time) >= s.`42`) AS \"42\",\n    SUM(TIME(sh.start_time) < s.`44` AND TIME(sh.end_time) >= s.`43`) AS \"43\",\n    SUM(TIME(sh.start_time) < s.`45` AND TIME(sh.end_time) >= s.`44`) AS \"44\",\n    SUM(TIME(sh.start_time) < s.`46` AND TIME(sh.end_time) >= s.`45`) AS \"45\",\n    SUM(TIME(sh.start_time) < s.`47` AND TIME(sh.end_time) >= s.`46`) AS \"46\",\n    SUM(TIME(sh.start_time) < s.`48` AND TIME(sh.end_time) >= s.`47`) AS \"47\",\n    SUM(TIME(sh.start_time) < s.`49` AND TIME(sh.end_time) >= s.`48`) AS \"48\",\n    SUM(TIME(sh.start_time) < s.`50` AND TIME(sh.end_time) >= s.`49`) AS \"49\",\n    SUM(TIME(sh.start_time) < s.`51` AND TIME(sh.end_time) >= s.`50`) AS \"50\",\n    SUM(TIME(sh.start_time) < s.`52` AND TIME(sh.end_time) >= s.`51`) AS \"51\",\n    SUM(TIME(sh.start_time) < s.`53` AND TIME(sh.end_time) >= s.`52`) AS \"52\",\n    SUM(TIME(sh.start_time) < s.`54` AND TIME(sh.end_time) >= s.`53`) AS \"53\",\n    SUM(TIME(sh.start_time) < s.`55` AND TIME(sh.end_time) >= s.`54`) AS \"54\",\n    SUM(TIME(sh.start_time) < s.`56` AND TIME(sh.end_time) >= s.`55`) AS \"55\",\n    SUM(TIME(sh.start_time) < s.`57` AND TIME(sh.end_time) >= s.`56`) AS \"56\",\n    SUM(TIME(sh.start_time) < s.`58` AND TIME(sh.end_time) >= s.`57`) AS \"57\",\n    SUM(TIME(sh.start_time) < s.`59` AND TIME(sh.end_time) >= s.`58`) AS \"58\",\n    SUM(TIME(sh.start_time) < s.`next` AND TIME(sh.end_time) >= s.`59`) AS \"59\"\nFROM\n    (\n        SELECT\n            s.seq AS \"Hour\",\n            MAKETIME(s.seq, 0, 0) AS \"00\",\n            MAKETIME(s.seq, 1, 0) AS \"01\",\n            MAKETIME(s.seq, 2, 0) AS \"02\",\n            MAKETIME(s.seq, 3, 0) AS \"03\",\n            MAKETIME(s.seq, 4, 0) AS \"04\",\n            MAKETIME(s.seq, 5, 0) AS \"05\",\n            MAKETIME(s.seq, 6, 0) AS \"06\",\n            MAKETIME(s.seq, 7, 0) AS \"07\",\n            MAKETIME(s.seq, 8, 0) AS \"08\",\n            MAKETIME(s.seq, 9, 0) AS \"09\",\n            MAKETIME(s.seq, 10, 0) AS \"10\",\n            MAKETIME(s.seq, 11, 0) AS \"11\",\n            MAKETIME(s.seq, 12, 0) AS \"12\",\n            MAKETIME(s.seq, 13, 0) AS \"13\",\n            MAKETIME(s.seq, 14, 0) AS \"14\",\n            MAKETIME(s.seq, 15, 0) AS \"15\",\n            MAKETIME(s.seq, 16, 0) AS \"16\",\n            MAKETIME(s.seq, 17, 0) AS \"17\",\n            MAKETIME(s.seq, 18, 0) AS \"18\",\n            MAKETIME(s.seq, 19, 0) AS \"19\",\n            MAKETIME(s.seq, 20, 0) AS \"20\",\n            MAKETIME(s.seq, 21, 0) AS \"21\",\n            MAKETIME(s.seq, 22, 0) AS \"22\",\n            MAKETIME(s.seq, 23, 0) AS \"23\",\n            MAKETIME(s.seq, 24, 0) AS \"24\",\n            MAKETIME(s.seq, 25, 0) AS \"25\",\n            MAKETIME(s.seq, 26, 0) AS \"26\",\n            MAKETIME(s.seq, 27, 0) AS \"27\",\n            MAKETIME(s.seq, 28, 0) AS \"28\",\n            MAKETIME(s.seq, 29, 0) AS \"29\",\n            MAKETIME(s.seq, 30, 0) AS \"30\",\n            MAKETIME(s.seq, 31, 0) AS \"31\",\n            MAKETIME(s.seq, 32, 0) AS \"32\",\n            MAKETIME(s.seq, 33, 0) AS \"33\",\n            MAKETIME(s.seq, 34, 0) AS \"34\",\n            MAKETIME(s.seq, 35, 0) AS \"35\",\n            MAKETIME(s.seq, 36, 0) AS \"36\",\n            MAKETIME(s.seq, 37, 0) AS \"37\",\n            MAKETIME(s.seq, 38, 0) AS \"38\",\n            MAKETIME(s.seq, 39, 0) AS \"39\",\n            MAKETIME(s.seq, 40, 0) AS \"40\",\n            MAKETIME(s.seq, 41, 0) AS \"41\",\n            MAKETIME(s.seq, 42, 0) AS \"42\",\n            MAKETIME(s.seq, 43, 0) AS \"43\",\n            MAKETIME(s.seq, 44, 0) AS \"44\",\n            MAKETIME(s.seq, 45, 0) AS \"45\",\n            MAKETIME(s.seq, 46, 0) AS \"46\",\n            MAKETIME(s.seq, 47, 0) AS \"47\",\n            MAKETIME(s.seq, 48, 0) AS \"48\",\n            MAKETIME(s.seq, 49, 0) AS \"49\",\n            MAKETIME(s.seq, 50, 0) AS \"50\",\n            MAKETIME(s.seq, 51, 0) AS \"51\",\n            MAKETIME(s.seq, 52, 0) AS \"52\",\n            MAKETIME(s.seq, 53, 0) AS \"53\",\n            MAKETIME(s.seq, 54, 0) AS \"54\",\n            MAKETIME(s.seq, 55, 0) AS \"55\",\n            MAKETIME(s.seq, 56, 0) AS \"56\",\n            MAKETIME(s.seq, 57, 0) AS \"57\",\n            MAKETIME(s.seq, 58, 0) AS \"58\",\n            MAKETIME(s.seq, 59, 0) AS \"59\",\n            MAKETIME(s.seq+1, 0, 0) AS \"next\"\n        FROM $dbname.seq_0_to_23 s\n    ) s,\n    $dbname.SessionHistory sh\nWHERE sh.user_id = $user\nGROUP BY s.Hour;"
      }
     ]
    },
    {
     "title": "Run times (last 90 days)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "dataset": "grafana",
       "rawSql": "SELECT\n    s.Hour AS \"Hour\",\n    SUM(TIME(sh.start_time) < s.`01` AND TIME(sh.end_time) >= s.`00`) AS \"00\",\n    SUM(TIME(sh.start_time) < s.`02` AND TIME(sh.end_time) >= s.`01`) AS \"01\",\n    SUM(TIME(sh.start_time) < s.`03` AND TIME(sh.end_time) >= s.`02`) AS \"02\",\n    SUM(TIME(sh.start_time) < s.`04` AND TIME(sh.end_time) >= s.`03`) AS \"03\",\n    SUM(TIME(sh.start_time) < s.`05` AND TIME(sh.end_time) >= s.`04`) AS \"04\",\n    SUM(TIME(sh.start_time) < s.`06` AND TIME(sh.end_time) >= s.`05`) AS \"05\",\n    SUM(TIME(sh.start_time) < s.`07` AND TIME(sh.end_time) >= s.`06`) AS \"06\",\n    SUM(TIME(sh.start_time) < s.`08` AND TIME(sh.end_time) >= s.`07`) AS \"07\",\n    SUM(TIME(sh.start_time) < s.`09` AND TIME(sh.end_time) >= s.`08`) AS \"08\",\n    SUM(TIME(sh.start_time) < s.`10` AND TIME(sh.end_time) >= s.`09`) AS \"09\",\n    SUM(TIME(sh.start_time) < s.`11` AND TIME(sh.end_time) >= s.`10`) AS \"10\",\n    SUM(TIME(sh.start_time) < s.`12` AND TIME(sh.end_time) >= s.`11`) AS \"11\",\n    SUM(TIME(sh.start_time) < s.`13` AND TIME(sh.end_time) >= s.`12`) AS \"12\",\n    SUM(TIME(sh.start_time) < s.`14` AND TIME(sh.end_time) >= s.`13`) AS \"13\",\n    SUM(TIME(sh.start_time) < s.`15` AND TIME(sh.end_time) >= s.`14`) AS \"14\",\n    SUM(TIME(sh.start_time) < s.`16` AND TIME(sh.end_time) >= s.`15`) AS \"15\",\n    SUM(TIME(sh.start_time) < s.`17` AND TIME(sh.end_time) >= s.`16`) AS \"16\",\n    SUM(TIME(sh.start_time) < s.`18` AND TIME(sh.end_time) >= s.`17`) AS \"17\",\n    SUM(TIME(sh.start_time) < s.`19` AND TIME(sh.end_time) >= s.`18`) AS \"18\",\n    SUM(TIME(sh.start_time) < s.`20` AND TIME(sh.end_time) >= s.`19`) AS \"19\",\n    SUM(TIME(sh.start_time) < s.`21` AND TIME(sh.end_time) >= s.`20`) AS \"20\",\n    SUM(TIME(sh.start_time) < s.`22` AND TIME(sh.end_time) >= s.`21`) AS \"21\",\n    SUM(TIME(sh.start_time) < s.`23` AND TIME(sh.end_time) >= s.`22`) AS \"22\",\n    SUM(TIME(sh.start_time) < s.`24` AND TIME(sh.end_time) >= s.`23`) AS \"23\",\n    SUM(TIME(sh.start_time) < s.`25` AND TIME(sh.end_time) >= s.`24`) AS \"24\",\n    SUM(TIME(sh.start_time) < s.`26` AND TIME(sh.end_time) >= s.`25`) AS \"25\",\n    SUM(TIME(sh.start_time) < s.`27` AND TIME(sh.end_time) >= s.`26`) AS \"26\",\n    SUM(TIME(sh.start_time) < s.`28` AND TIME(sh.end_time) >= s.`27`) AS \"27\",\n    SUM(TIME(sh.start_time) < s.`29` AND TIME(sh.end_time) >= s.`28`) AS \"28\",\n    SUM(TIME(sh.start_time) < s.`30` AND TIME(sh.end_time) >= s.`29`) AS \"29\",\n    SUM(TIME(sh.start_time) < s.`31` AND TIME(sh.end_time) >= s.`30`) AS \"30\",\n    SUM(TIME(sh.start_time) < s.`32` AND TIME(sh.end_time) >= s.`31`) AS \"31\",\n    SUM(TIME(sh.start_time) < s.`33` AND TIME(sh.end_time) >= s.`32`) AS \"32\",\n    SUM(TIME(sh.start_time) < s.`34` AND TIME(sh.end_time) >= s.`33`) AS \"33\",\n    SUM(TIME(sh.start_time) < s.`35` AND TIME(sh.end_time) >= s.`34`) AS \"34\",\n    SUM(TIME(sh.start_time) < s.`36` AND TIME(sh.end_time) >= s.`35`) AS \"35\",\n    SUM(TIME(sh.start_time) < s.`37` AND TIME(sh.end_time) >= s.`36`) AS \"36\",\n    SUM(TIME(sh.start_time) < s.`38` AND TIME(sh.end_time) >= s.`37`) AS \"37\",\n    SUM(TIME(sh.start_time) < s.`39` AND TIME(sh.end_time) >= s.`38`) AS \"38\",\n    SUM(TIME(sh.start_time) < s.`40` AND TIME(sh.end_time) >= s.`39`) AS \"39\",\n    SUM(TIME(sh.start_time) < s.`41` AND TIME(sh.end_time) >= s.`40`) AS \"40\",\n    SUM(TIME(sh.start_time) < s.`42` AND TIME(sh.end_time) >= s.`41`) AS \"41\",\n    SUM(TIME(sh.start_time) < s.`43` AND TIME(sh.end_time) >= s.`42`) AS \"42\",\n    SUM(TIME(sh.start_time) < s.`44` AND TIME(sh.end_time) >= s.`43`) AS \"43\",\n    SUM(TIME(sh.start_time) < s.`45` AND TIME(sh.end_time) >= s.`44`) AS \"44\",\n    SUM(TIME(sh.start_time) < s.`46` AND TIME(sh.end_time) >= s.`45`) AS \"45\",\n    SUM(TIME(sh.start_time) < s.`47` AND TIME(sh.end_time) >= s.`46`) AS \"46\",\n    SUM(TIME(sh.start_time) < s.`48` AND TIME(sh.end_time) >= s.`47`) AS \"47\",\n    SUM(TIME(sh.start_time) < s.`49` AND TIME(sh.end_time) >= s.`48`) AS \"48\",\n    SUM(TIME(sh.start_time) < s.`50` AND TIME(sh.end_time) >= s.`49`) AS \"49\",\n    SUM(TIME(sh.start_time) < s.`51` AND TIME(sh.end_time) >= s.`50`) AS \"50\",\n    SUM(TIME(sh.start_time) < s.`52` AND TIME(sh.end_time) >= s.`51`) AS \"51\",\n    SUM(TIME(sh.start_time) < s.`53` AND TIME(sh.end_time) >= s.`52`) AS \"52\",\n    SUM(TIME(sh.start_time) < s.`54` AND TIME(sh.end_time) >= s.`53`) AS \"53\",\n    SUM(TIME(sh.start_time) < s.`55` AND TIME(sh.end_time) >= s.`54`) AS \"54\",\n    SUM(TIME(sh.start_time) < s.`56` AND TIME(sh.end_time) >= s.`55`) AS \"55\",\n    SUM(TIME(sh.start_time) < s.`57` AND TIME(sh.end_time) >= s.`56`) AS \"56\",\n    SUM(TIME(sh.start_time) < s.`58` AND TIME(sh.end_time) >= s.`57`) AS \"57\",\n    SUM(TIME(sh.start_time) < s.`59` AND TIME(sh.end_time) >= s.`58`) AS \"58\",\n    SUM(TIME(sh.start_time) < s.`next` AND TIME(sh.end_time) >= s.`59`) AS \"59\"\nFROM\n    (\n        SELECT\n            s.seq AS \"Hour\",\n            MAKETIME(s.seq, 0, 0) AS \"00\",\n            MAKETIME(s.seq, 1, 0) AS \"01\",\n            MAKETIME(s.seq, 2, 0) AS \"02\",\n            MAKETIME(s.seq, 3, 0) AS \"03\",\n            MAKETIME(s.seq, 4, 0) AS \"04\",\n            MAKETIME(s.seq, 5, 0) AS \"05\",\n            MAKETIME(s.seq, 6, 0) AS \"06\",\n            MAKETIME(s.seq, 7, 0) AS \"07\",\n            MAKETIME(s.seq, 8, 0) AS \"08\",\n            MAKETIME(s.seq, 9, 0) AS \"09\",\n            MAKETIME(s.seq, 10, 0) AS \"10\",\n            MAKETIME(s.seq, 11, 0) AS \"11\",\n            MAKETIME(s.seq, 12, 0) AS \"12\",\n            MAKETIME(s.seq, 13, 0) AS \"13\",\n            MAKETIME(s.seq, 14, 0) AS \"14\",\n            MAKETIME(s.seq, 15, 0) AS \"15\",\n            MAKETIME(s.seq, 16, 0) AS \"16\",\n            MAKETIME(s.seq, 17, 0) AS \"17\",\n            MAKETIME(s.seq, 18, 0) AS \"18\",\n            MAKETIME(s.seq, 19, 0) AS \"19\",\n            MAKETIME(s.seq, 20, 0) AS \"20\",\n            MAKETIME(s.seq, 21, 0) AS \"21\",\n            MAKETIME(s.seq, 22, 0) AS \"22\",\n            MAKETIME(s.seq, 23, 0) AS \"23\",\n            MAKETIME(s.seq, 24, 0) AS \"24\",\n            MAKETIME(s.seq, 25, 0) AS \"25\",\n            MAKETIME(s.seq, 26, 0) AS \"26\",\n            MAKETIME(s.seq, 27, 0) AS \"27\",\n            MAKETIME(s.seq, 28, 0) AS \"28\",\n            MAKETIME(s.seq, 29, 0) AS \"29\",\n            MAKETIME(s.seq, 30, 0) AS \"30\",\n            MAKETIME(s.seq, 31, 0) AS \"31\",\n            MAKETIME(s.seq, 32, 0) AS \"32\",\n            MAKETIME(s.seq, 33, 0) AS \"33\",\n            MAKETIME(s.seq, 34, 0) AS \"34\",\n            MAKETIME(s.seq, 35, 0) AS \"35\",\n            MAKETIME(s.seq, 36, 0) AS \"36\",\n            MAKETIME(s.seq, 37, 0) AS \"37\",\n            MAKETIME(s.seq, 38, 0) AS \"38\",\n            MAKETIME(s.seq, 39, 0) AS \"39\",\n            MAKETIME(s.seq, 40, 0) AS \"40\",\n            MAKETIME(s.seq, 41, 0) AS \"41\",\n            MAKETIME(s.seq, 42, 0) AS \"42\",\n            MAKETIME(s.seq, 43, 0) AS \"43\",\n            MAKETIME(s.seq, 44, 0) AS \"44\",\n            MAKETIME(s.seq, 45, 0) AS \"45\",\n            MAKETIME(s.seq, 46, 0) AS \"46\",\n            MAKETIME(s.seq, 47, 0) AS \"47\",\n            MAKETIME(s.seq, 48, 0) AS \"48\",\n            MAKETIME(s.seq, 49, 0) AS \"49\",\n            MAKETIME(s.seq, 50, 0) AS \"50\",\n            MAKETIME(s.seq, 51, 0) AS \"51\",\n            MAKETIME(s.seq, 52, 0) AS \"52\",\n            MAKETIME(s.seq, 53, 0) AS \"53\",\n            MAKETIME(s.seq, 54, 0) AS \"54\",\n            MAKETIME(s.seq, 55, 0) AS \"55\",\n            MAKETIME(s.seq, 56, 0) AS \"56\",\n            MAKETIME(s.seq, 57, 0) AS \"57\",\n            MAKETIME(s.seq, 58, 0) AS \"58\",\n            MAKETIME(s.seq, 59, 0) AS \"59\",\n            MAKETIME(s.seq+1, 0, 0) AS \"next\"\n        FROM $dbname.seq_0_to_23 s\n    ) s,\n    $dbname.SessionHistory sh\nWHERE sh.user_id = $user\n  AND TIMESTAMPDIFF(DAY, sh.timestamp, NOW()) <= 90\nGROUP BY s.Hour;"
      }
     ]
    }
   ]
  }
 ]
}